#!/usr/bin/env bash
#
# Regenerate the nav with gen_nav.py and splice it into zensical.toml,
# replacing whatever currently sits between the two marker lines.
#
# One-time setup: add these two lines inside the [project] table of
# zensical.toml (before any [project.xxx] sub-table):
#
#   # >>> BEGIN AUTOGENERATED NAV (managed by gen_nav.py) >>>
#   # <<< END AUTOGENERATED NAV <<<
#
# Usage:  ./update_nav.sh [path/to/zensical.toml]
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOML="${1:-$SCRIPT_DIR/zensical.toml}"
GEN="$SCRIPT_DIR/gen_nav.py"
PROJECT_DIR="$(cd "$(dirname "$TOML")" && pwd)"   # gen_nav.py resolves docs/ from here

BEGIN_MARK="BEGIN AUTOGENERATED NAV"
END_MARK="END AUTOGENERATED NAV"

[[ -f "$TOML" ]] || { echo "error: $TOML not found" >&2; exit 1; }
grep -qF "$BEGIN_MARK" "$TOML" && grep -qF "$END_MARK" "$TOML" || {
  echo "error: nav markers not found in $TOML." >&2
  echo "Add these two lines inside your [project] table, then re-run:" >&2
  echo "  # >>> BEGIN AUTOGENERATED NAV (managed by gen_nav.py) >>>" >&2
  echo "  # <<< END AUTOGENERATED NAV <<<" >&2
  exit 1
}

TMP_NAV="$(mktemp)"
TMP_TOML="$(mktemp)"
trap 'rm -f "$TMP_NAV" "$TMP_TOML"' EXIT

# 1. generate the nav block (run from the project dir so docs/ resolves)
( cd "$PROJECT_DIR" && python3 "$GEN" ) > "$TMP_NAV"

# 2. splice it between the markers, dropping the old block
awk -v navfile="$TMP_NAV" '
  index($0, "BEGIN AUTOGENERATED NAV") {
    print
    while ((getline line < navfile) > 0) print line
    close(navfile)
    inblock = 1
    next
  }
  index($0, "END AUTOGENERATED NAV") { inblock = 0; print; next }
  !inblock { print }
' "$TOML" > "$TMP_TOML"

# 3. only overwrite if the result is still valid TOML (best-effort)
if python3 - "$TMP_TOML" <<'PY'
import sys
try:
    import tomllib
except ModuleNotFoundError:
    sys.exit(0)          # older Python: skip validation rather than block
with open(sys.argv[1], "rb") as f:
    tomllib.load(f)
PY
then
  cp "$TOML" "$TOML.bak"
  cp "$TMP_TOML" "$TOML"
  echo "Updated nav in $TOML  (backup saved to $TOML.bak)"
else
  echo "error: generated TOML failed to parse; $TOML left unchanged." >&2
  exit 1
fi
